// Fiktive, frei erfundene Anzeigenamen je Track (Dateiname -> Titel).
// Bewusst ohne Bezug zu den echten Dateinamen.
var MUSIK_NAMEN = {
  "Stardew_Valley_OST_-_A_Dark_Corner_Of_The_Past.mp3": "Morgentau",
  "Stardew_Valley_OST_-_A_Glimpse_Of_The_Other_World_(Wizard's_Theme).mp3": "Goldene Ähren",
  "Stardew_Valley_OST_-_Alex's_Keepsake.mp3": "Stiller Teich",
  "Stardew_Valley_OST_-_Band_Practice.mp3": "Lampenlicht",
  "Stardew_Valley_OST_-_Cloud_Country.mp3": "Heuboden-Walzer",
  "Stardew_Valley_OST_-_Dance_Of_The_Moonlight_Jellies.mp3": "Apfelblüte",
  "Stardew_Valley_OST_-_Distant_Banjo.mp3": "Sonntagsmarkt",
  "Stardew_Valley_OST_-_Echos_(Sebastian's_Theme).mp3": "Nebel über der Wiese",
  "Stardew_Valley_OST_-_Fall_(Ghost_Synth).mp3": "Kastanienweg",
  "Stardew_Valley_OST_-_Fall_(Raven's_Descent).mp3": "Abendglocken",
  "Stardew_Valley_OST_-_Fall_(The_Smell_of_Mushroom).mp3": "Kürbisernte",
  "Stardew_Valley_OST_-_Festival_Game.mp3": "Regen auf dem Dach",
  "Stardew_Valley_OST_-_Flower_Dance.mp3": "Bienensummen",
  "Stardew_Valley_OST_-_Fun_Festival.mp3": "Erste Aussaat",
  "Stardew_Valley_OST_-_Grandpa's_Theme.mp3": "Kaminfeuer",
  "Stardew_Valley_OST_-_Grapefruit_Sky_(Dr._Harvey's_Theme).mp3": "Sternenklare Nacht",
  "Stardew_Valley_OST_-_In_The_Deep_Woods.mp3": "Waldlichtung",
  "Stardew_Valley_OST_-_Jaunty.mp3": "Barfuß im Gras",
  "Stardew_Valley_OST_-_Journey_Of_The_Prairie_King_-_Final_Boss_&_Ending.mp3": "Der alte Brunnen",
  "Stardew_Valley_OST_-_Journey_Of_The_Prairie_King_-_Overworld.mp3": "Windmühle",
  "Stardew_Valley_OST_-_Journey_Of_The_Prairie_King_-_The_Outlaw.mp3": "Erdbeerfeld",
  "Stardew_Valley_OST_-_Load_Game.mp3": "Milchkanne",
  "Stardew_Valley_OST_-_Luau_Festival.mp3": "Dorffest",
  "Stardew_Valley_OST_-_Mines_(A_Flicker_In_the_Deep).mp3": "Tau im Klee",
  "Stardew_Valley_OST_-_Mines_(Cloth).mp3": "Lavendelduft",
  "Stardew_Valley_OST_-_Mines_(Crystal_Bells).mp3": "Honigglas",
  "Stardew_Valley_OST_-_Mines_(Danger!).mp3": "Gewitterluft",
  "Stardew_Valley_OST_-_Mines_(Icicles).mp3": "Frostmuster",
  "Stardew_Valley_OST_-_Mines_(Magical_Shoes).mp3": "Holzschuhe",
  "Stardew_Valley_OST_-_Mines_(Marimba_Of_Frozen_Bone).mp3": "Eisblumen",
  "Stardew_Valley_OST_-_Mines_(Star_Lumpy).mp3": "Glühwürmchen",
  "Stardew_Valley_OST_-_Mines_(The_Lava_Dwellers).mp3": "Rote Scheune",
  "Stardew_Valley_OST_-_Mines_(Visitor_To_The_Unknown).mp3": "Fremder Gast",
  "Stardew_Valley_OST_-_Music_Box_Song.mp3": "Spieldose",
  "Stardew_Valley_OST_-_Pelican_Town.mp3": "Krähennest",
  "Stardew_Valley_OST_-_Pickle_Jar_Rag_(Haley's_Theme).mp3": "Sauerteig",
  "Stardew_Valley_OST_-_Sam's_Band_(Bluegrass).mp3": "Fiedel am Abend",
  "Stardew_Valley_OST_-_Sam's_Band_(Electronic).mp3": "Flimmernde Saiten",
  "Stardew_Valley_OST_-_Sam's_Band_(Heavy).mp3": "Trommelwirbel",
  "Stardew_Valley_OST_-_Sam's_Band_(Pop).mp3": "Marktschreier",
  "Stardew_Valley_OST_-_Settling_In.mp3": "Neues Zuhause",
  "Stardew_Valley_OST_-_Spirit's_Eve_Festival.mp3": "Laternenumzug",
  "Stardew_Valley_OST_-_Spring_(It's_a_Big_World_Outside).mp3": "Frühlingsregen",
  "Stardew_Valley_OST_-_Spring_(The_Valley_Comes_Alive).mp3": "Krokusse",
  "Stardew_Valley_OST_-_Spring_(Wild_Horseradish_Jam).mp3": "Kräutergarten",
  "Stardew_Valley_OST_-_Stardew_Valley_Fair_Theme.mp3": "Erntedank",
  "Stardew_Valley_OST_-_Stardew_Valley_Overture.mp3": "Sonnenaufgang",
  "Stardew_Valley_OST_-_Summer_(Nature's_Crescendo).mp3": "Heiße Mittagsstunde",
  "Stardew_Valley_OST_-_Summer_(The_Sun_Can_Bend_An_Orange_Sky).mp3": "Reife Tomaten",
  "Stardew_Valley_OST_-_Summer_(Tropicala).mp3": "Zitronenlimonade",
  "Stardew_Valley_OST_-_The_Adventure_Guild.mp3": "Über die Hügel",
  "Stardew_Valley_OST_-_The_Library_and_Museum.mp3": "Staubige Bücher",
  "Stardew_Valley_OST_-_The_Stardrop_Saloon.mp3": "Zum krummen Krug",
  "Stardew_Valley_OST_-_Violin_Solo.mp3": "Einsame Geige",
  "Stardew_Valley_OST_-_Wedding_Celebration.mp3": "Blumenkranz",
  "Stardew_Valley_OST_-_Winter_(Ancient).mp3": "Erster Schnee",
  "Stardew_Valley_OST_-_Winter_(Nocturne_of_Ice).mp3": "Mondlicht auf Eis",
  "Stardew_Valley_OST_-_Winter_Festival.mp3": "Winterstille",
};
